In [1]:
!pip install datasets
!pip install pandas

Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.11)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 7.3 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.1 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 10.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.4 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 9.1 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.5.1+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.5.1+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.5.1+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.5.1+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

from google.colab import drive
from typing import List
from datasets import Dataset, ClassLabel, DatasetDict

In [3]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
df = pd.read_csv('./drive/MyDrive/questoes/base_de_conhecimento/questoes.csv')
df.head()

,titulo_do_texto,texto,descritor,comando,resposta_item,resposta,opcoes,ano,tipo,origem
0,Entenda como se forma um arco-íris!,O arco colorido surge quando os raios de luz d...,D23 - Identificar os níveis de linguagem e/ou ...,A linguagem utilizada no trecho “Quando observ...,c,formal.,"['científica.', 'coloquial.\r', 'formal.', 're...",6° ano,SPAECE,Avaliação paraná
1,Tomar banho depois de comer faz mal?,"Na verdade, não é indicado tomar banho de imer...",D23 - Identificar os níveis de linguagem e/ou ...,No trecho “... diminuir os pulsos e daí você s...,d,se fala no dia a dia.,"['é falada em uma região do país. ', 'é utiliz...",6° ano,SPAECE,Avaliação paraná
2,Blog da Galera: Minha aventura para ver o show...,"Isabella Vieira, da Galera CAPRICHO, foi atrás...",D23 - Identificar os níveis de linguagem e/ou ...,"Nesse texto, no trecho “E aí, galera!? Aqui qu...",a,conversas entre amigos.,"['conversas entre amigos.\r', 'discursos polít...",6° ano,SPAECE,Avaliação paraná
3,Lagosta “algodão­doce”: o que explica essa col...,"Um grupo de pescadores dos EUA1 , teve uma enc...",D23 - Identificar os níveis de linguagem e/ou ...,"Nesse texto, o trecho: “No entanto, biólogos m...",d,formal,"['coloquial.', 'técnica.', 'antiga.', 'formal']",6° ano,SPAECE,Avaliação paraná
4,-,"Beto Oi! Meu nome é Beto e vivo na Zoolândia, ...",D23 - Identificar os níveis de linguagem e/ou ...,"Nesse texto, no trecho “... vivo na Zoolândia,...",b,informal.,"['científica.', 'informal.', 'padrão.', 'regio...",6° ano,SPAECE,Avaliação paraná

In [6]:
df = df.dropna()
df.isnull().values.any()

False

In [7]:
descriptor_table = df['descritor'].value_counts().reset_index()
descriptor_table.columns = ['descritor', 'quantidade']
descriptor_table

                                            descritor  quantidade
0   D06 - Distinguir fato de opinião relativa ao f...          38
1   D23 - Identificar os níveis de linguagem e/ou ...          33
2    D05 - Identificar o tema ou assunto de um texto.          33
3   D20 - Reconhecer o efeito de sentido decorrent...          30
4   D01 - Localizar informações explícitas em um t...          27
5   D19 – Reconhecer o efeito de sentido decorrent...          25
6   D17 - Reconhecer o sentido das relações lógico...          23
7   D11 - Reconhecer os elementos que compõem uma ...          22
8   D21 - Reconhecer o efeito decorrente do empreg...          20
9   D07 - Diferenciar a informação principal das s...          20
10  D14 - Reconhecer as relações entre partes de u...          19
11  D03 - Inferir o sentido de uma palavra ou expr...          16
12        D22 - Reconhecer efeitos de humor e ironia.          10
13                D09 - Reconhecer gênero discursivo.           4
14  D10 - Identificar o propósito comunicativo em ...           3
15      D22 - Reconhecer efeitos de humor e ironia.\n           1

In [8]:
dataset = Dataset.from_pandas(df)

dataset = dataset.map(lambda example: {"descritor_codigo": example["descritor"].split(" - ")[0]})
unique_descritores_codigos = list(set(dataset['descritor_codigo']))
dataset = dataset.cast_column('descritor_codigo', ClassLabel(names=unique_descritores_codigos))

split = dataset.train_test_split(test_size=0.1, stratify_by_column='descritor_codigo', seed=42)

dataset_dict = DatasetDict({
    'train': split['train'],
    'validation': split['test']
})

split_train = dataset_dict['train'].train_test_split(test_size=0.1, stratify_by_column='descritor_codigo', seed=42)

dataset_dict['train'] = split_train['train']
dataset_dict['test'] = split_train['test']

dataset_dict['train'].to_csv('dataset_treino.csv', index=False)
dataset_dict['validation'].to_csv('dataset_validacao.csv', index=False)
dataset_dict['test'].to_csv('dataset_test.csv', index=False)

Map:   0%|          | 0/324 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/324 [00:00<?, ? examples/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

48996